### PR TITLE
Implement merch page color hover & select and thumbnails

### PR DESCRIPTION
**Pull request by jibranabsarulislam**
Uses latest main to refactor and solve what should be left of the merch page (#1 #2 #3 #4 #5 #6 #9).

b01962b also refactors id names and merch handler function for reusability and maintainability 

https://github.com/cumathsoc/cumathsoc.github.io/assets/70596906/5b62758a-a091-4278-a14a-700e02e212eb

### CODE REVIEW

**Comment by jibranabsarulislam** [comment]
from a ux perspective i'd pitch persisting the selected thumbnail when the color changes (i.e. keep the back shown when color goes from black to red). this would be implemented similarly to colorStore, which is how the color text restores when the mouse leaves the color selector

**Review by zakuArbor — APPROVED** [review]
Looks good. Thanks for your contribution and for that video.

**Comment by zakuArbor** [comment]
> from a ux perspective i'd pitch persisting the selected thumbnail when the color changes (i.e. keep the back shown when color goes from black to red). this would be implemented similarly to colorStore, which is how the color text restores when the mouse leaves the color selector

I agree. It is a bit annoying to see the shirt change sides

**Comment by zakuArbor** [comment]
I do like your proposed changes to have a border around the selected thumbnails as well. It makes it clear what has been selected as well.

**Pull request merged**
